package com.bonade.xxp.xqc_android_im.DB.entity;

import com.bonade.xxp.xqc_android_im.protobuf.helper.EntityChangeEngine;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "Session".
 */
@Entity(nameInDb = "Session")
public class SessionEntity {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    private String sessionKey;
    private Integer peerId;
    private Integer peerType;
    private Integer latestMsgType;
    private Integer latestMsgId;
    private String latestMsgData;
    private Integer talkId;
    private Integer created;
    private Integer updated;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public SessionEntity() {
    }

    public SessionEntity(Long id) {
        this.id = id;
    }

    @Generated
    public SessionEntity(Long id, String sessionKey, Integer peerId, Integer peerType, Integer latestMsgType, Integer latestMsgId, String latestMsgData, Integer talkId, Integer created, Integer updated) {
        this.id = id;
        this.sessionKey = sessionKey;
        this.peerId = peerId;
        this.peerType = peerType;
        this.latestMsgType = latestMsgType;
        this.latestMsgId = latestMsgId;
        this.latestMsgData = latestMsgData;
        this.talkId = talkId;
        this.created = created;
        this.updated = updated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getSessionKey() {
        return sessionKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSessionKey(@NotNull String sessionKey) {
        this.sessionKey = sessionKey;
    }

    public Integer getPeerId() {
        return peerId;
    }

    public void setPeerId(Integer peerId) {
        this.peerId = peerId;
    }

    public Integer getPeerType() {
        return peerType;
    }

    public void setPeerType(Integer peerType) {
        this.peerType = peerType;
    }

    public Integer getLatestMsgType() {
        return latestMsgType;
    }

    public void setLatestMsgType(Integer latestMsgType) {
        this.latestMsgType = latestMsgType;
    }

    public Integer getLatestMsgId() {
        return latestMsgId;
    }

    public void setLatestMsgId(Integer latestMsgId) {
        this.latestMsgId = latestMsgId;
    }

    public String getLatestMsgData() {
        return latestMsgData;
    }

    public void setLatestMsgData(String latestMsgData) {
        this.latestMsgData = latestMsgData;
    }

    public Integer getTalkId() {
        return talkId;
    }

    public void setTalkId(Integer talkId) {
        this.talkId = talkId;
    }

    public Integer getCreated() {
        return created;
    }

    public void setCreated(Integer created) {
        this.created = created;
    }

    public Integer getUpdated() {
        return updated;
    }

    public void setUpdated(Integer updated) {
        this.updated = updated;
    }

    // KEEP METHODS - put your custom methods here
    public String buildSessionKey() {
        if (peerType <= 0 || peerId <= 0) {
            throw new IllegalArgumentException(
                    "SessionEntity buildSessionKey error,cause by some params <=0");
        }
        sessionKey = EntityChangeEngine.getSessionKey(peerId, peerType);
        return sessionKey;
    }
    // KEEP METHODS END

}
