package com.bonade.xxp.xqc_android_im.DB.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bonade.xxp.xqc_android_im.DB.entity.GroupEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GroupInfo".
*/
public class GroupDao extends AbstractDao<GroupEntity, Long> {

    public static final String TABLENAME = "GroupInfo";

    /**
     * Properties of entity GroupEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Cid = new Property(0, Long.class, "cid", true, "CID");
        public final static Property PeerId = new Property(1, int.class, "peerId", false, "PEER_ID");
        public final static Property GroupType = new Property(2, Integer.class, "groupType", false, "GROUP_TYPE");
        public final static Property MainName = new Property(3, String.class, "mainName", false, "MAIN_NAME");
        public final static Property Avatar = new Property(4, String.class, "avatar", false, "AVATAR");
        public final static Property CreatorId = new Property(5, Integer.class, "creatorId", false, "CREATOR_ID");
        public final static Property UserCount = new Property(6, Integer.class, "userCount", false, "USER_COUNT");
        public final static Property UserIds = new Property(7, String.class, "userIds", false, "USER_IDS");
        public final static Property Version = new Property(8, Integer.class, "version", false, "VERSION");
        public final static Property Status = new Property(9, Integer.class, "status", false, "STATUS");
        public final static Property Created = new Property(10, Integer.class, "created", false, "CREATED");
        public final static Property Updated = new Property(11, Integer.class, "updated", false, "UPDATED");
    }


    public GroupDao(DaoConfig config) {
        super(config);
    }
    
    public GroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GroupInfo\" (" + //
                "\"CID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: cid
                "\"PEER_ID\" INTEGER NOT NULL UNIQUE ," + // 1: peerId
                "\"GROUP_TYPE\" INTEGER," + // 2: groupType
                "\"MAIN_NAME\" TEXT," + // 3: mainName
                "\"AVATAR\" TEXT," + // 4: avatar
                "\"CREATOR_ID\" INTEGER," + // 5: creatorId
                "\"USER_COUNT\" INTEGER," + // 6: userCount
                "\"USER_IDS\" TEXT," + // 7: userIds
                "\"VERSION\" INTEGER," + // 8: version
                "\"STATUS\" INTEGER," + // 9: status
                "\"CREATED\" INTEGER," + // 10: created
                "\"UPDATED\" INTEGER);"); // 11: updated
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GroupInfo\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GroupEntity entity) {
        stmt.clearBindings();
 
        Long cid = entity.getCid();
        if (cid != null) {
            stmt.bindLong(1, cid);
        }
        stmt.bindLong(2, entity.getPeerId());
 
        Integer groupType = entity.getGroupType();
        if (groupType != null) {
            stmt.bindLong(3, groupType);
        }
 
        String mainName = entity.getMainName();
        if (mainName != null) {
            stmt.bindString(4, mainName);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(5, avatar);
        }
 
        Integer creatorId = entity.getCreatorId();
        if (creatorId != null) {
            stmt.bindLong(6, creatorId);
        }
 
        Integer userCount = entity.getUserCount();
        if (userCount != null) {
            stmt.bindLong(7, userCount);
        }
 
        String userIds = entity.getUserIds();
        if (userIds != null) {
            stmt.bindString(8, userIds);
        }
 
        Integer version = entity.getVersion();
        if (version != null) {
            stmt.bindLong(9, version);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(10, status);
        }
 
        Integer created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(11, created);
        }
 
        Integer updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(12, updated);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GroupEntity entity) {
        stmt.clearBindings();
 
        Long cid = entity.getCid();
        if (cid != null) {
            stmt.bindLong(1, cid);
        }
        stmt.bindLong(2, entity.getPeerId());
 
        Integer groupType = entity.getGroupType();
        if (groupType != null) {
            stmt.bindLong(3, groupType);
        }
 
        String mainName = entity.getMainName();
        if (mainName != null) {
            stmt.bindString(4, mainName);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(5, avatar);
        }
 
        Integer creatorId = entity.getCreatorId();
        if (creatorId != null) {
            stmt.bindLong(6, creatorId);
        }
 
        Integer userCount = entity.getUserCount();
        if (userCount != null) {
            stmt.bindLong(7, userCount);
        }
 
        String userIds = entity.getUserIds();
        if (userIds != null) {
            stmt.bindString(8, userIds);
        }
 
        Integer version = entity.getVersion();
        if (version != null) {
            stmt.bindLong(9, version);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(10, status);
        }
 
        Integer created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(11, created);
        }
 
        Integer updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(12, updated);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GroupEntity readEntity(Cursor cursor, int offset) {
        GroupEntity entity = new GroupEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // cid
            cursor.getInt(offset + 1), // peerId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // groupType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mainName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // avatar
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // creatorId
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // userCount
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // userIds
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // version
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // status
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // created
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11) // updated
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GroupEntity entity, int offset) {
        entity.setCid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPeerId(cursor.getInt(offset + 1));
        entity.setGroupType(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setMainName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAvatar(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCreatorId(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setUserCount(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setUserIds(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setVersion(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setStatus(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setCreated(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setUpdated(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GroupEntity entity, long rowId) {
        entity.setCid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GroupEntity entity) {
        if(entity != null) {
            return entity.getCid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GroupEntity entity) {
        return entity.getCid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
