package com.bonade.xxp.xqc_android_im.DB.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bonade.xxp.xqc_android_im.DB.entity.SessionEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Session".
*/
public class SessionDao extends AbstractDao<SessionEntity, Long> {

    public static final String TABLENAME = "Session";

    /**
     * Properties of entity SessionEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SessionKey = new Property(1, String.class, "sessionKey", false, "SESSION_KEY");
        public final static Property PeerId = new Property(2, Integer.class, "peerId", false, "PEER_ID");
        public final static Property PeerType = new Property(3, Integer.class, "peerType", false, "PEER_TYPE");
        public final static Property LatestMsgType = new Property(4, Integer.class, "latestMsgType", false, "LATEST_MSG_TYPE");
        public final static Property LatestMsgId = new Property(5, Integer.class, "latestMsgId", false, "LATEST_MSG_ID");
        public final static Property LatestMsgData = new Property(6, String.class, "latestMsgData", false, "LATEST_MSG_DATA");
        public final static Property TalkId = new Property(7, Integer.class, "talkId", false, "TALK_ID");
        public final static Property Created = new Property(8, Integer.class, "created", false, "CREATED");
        public final static Property Updated = new Property(9, Integer.class, "updated", false, "UPDATED");
    }


    public SessionDao(DaoConfig config) {
        super(config);
    }
    
    public SessionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"Session\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SESSION_KEY\" TEXT NOT NULL UNIQUE ," + // 1: sessionKey
                "\"PEER_ID\" INTEGER," + // 2: peerId
                "\"PEER_TYPE\" INTEGER," + // 3: peerType
                "\"LATEST_MSG_TYPE\" INTEGER," + // 4: latestMsgType
                "\"LATEST_MSG_ID\" INTEGER," + // 5: latestMsgId
                "\"LATEST_MSG_DATA\" TEXT," + // 6: latestMsgData
                "\"TALK_ID\" INTEGER," + // 7: talkId
                "\"CREATED\" INTEGER," + // 8: created
                "\"UPDATED\" INTEGER);"); // 9: updated
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"Session\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SessionEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSessionKey());
 
        Integer peerId = entity.getPeerId();
        if (peerId != null) {
            stmt.bindLong(3, peerId);
        }
 
        Integer peerType = entity.getPeerType();
        if (peerType != null) {
            stmt.bindLong(4, peerType);
        }
 
        Integer latestMsgType = entity.getLatestMsgType();
        if (latestMsgType != null) {
            stmt.bindLong(5, latestMsgType);
        }
 
        Integer latestMsgId = entity.getLatestMsgId();
        if (latestMsgId != null) {
            stmt.bindLong(6, latestMsgId);
        }
 
        String latestMsgData = entity.getLatestMsgData();
        if (latestMsgData != null) {
            stmt.bindString(7, latestMsgData);
        }
 
        Integer talkId = entity.getTalkId();
        if (talkId != null) {
            stmt.bindLong(8, talkId);
        }
 
        Integer created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(9, created);
        }
 
        Integer updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(10, updated);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SessionEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSessionKey());
 
        Integer peerId = entity.getPeerId();
        if (peerId != null) {
            stmt.bindLong(3, peerId);
        }
 
        Integer peerType = entity.getPeerType();
        if (peerType != null) {
            stmt.bindLong(4, peerType);
        }
 
        Integer latestMsgType = entity.getLatestMsgType();
        if (latestMsgType != null) {
            stmt.bindLong(5, latestMsgType);
        }
 
        Integer latestMsgId = entity.getLatestMsgId();
        if (latestMsgId != null) {
            stmt.bindLong(6, latestMsgId);
        }
 
        String latestMsgData = entity.getLatestMsgData();
        if (latestMsgData != null) {
            stmt.bindString(7, latestMsgData);
        }
 
        Integer talkId = entity.getTalkId();
        if (talkId != null) {
            stmt.bindLong(8, talkId);
        }
 
        Integer created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(9, created);
        }
 
        Integer updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(10, updated);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SessionEntity readEntity(Cursor cursor, int offset) {
        SessionEntity entity = new SessionEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // sessionKey
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // peerId
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // peerType
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // latestMsgType
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // latestMsgId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // latestMsgData
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // talkId
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // created
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9) // updated
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SessionEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSessionKey(cursor.getString(offset + 1));
        entity.setPeerId(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setPeerType(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setLatestMsgType(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setLatestMsgId(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setLatestMsgData(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTalkId(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setCreated(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setUpdated(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SessionEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SessionEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SessionEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
